version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      # - ./data/db:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/appuser
    ports:
      - 8000:80
    depends_on:
      - db
